app = "wp-with-volume"
primary_region = 'iad'
kill_signal = 'SIGINT'

[[vm]]
  memory = '0.25gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
WORDPRESS_CONFIG_EXTRA = "define(\"MYSQL_CLIENT_FLAGS\", MYSQLI_CLIENT_SSL);"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
handlers = ["tls", "http"]
port = 443


[mounts]
  source="wp_content_volume"
  destination="/var/www/html/wp-content"
  initial_size = "1gb"

