app = 'wordpress-one'
primary_region = 'iad'
kill_signal = 'SIGINT'

[[vm]]
  memory = '0.25gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'maria_storage'
  destination = '/var/lib/mysql'

[env]
  MARIADB_DATABASE = 'database_master'
  MARIADB_USER = 'useradmin'
  WORDPRESS_CONFIG_EXTRA = "define('WP_HOME', 'https://fly.kitestringstudio.com'); define( 'WP_SITEURL', WP_HOME );"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

